#!/usr/bin/env bash
declare -A repositories
if [ $1 == 'add' ]
then
REPO_NAME=$2
REPO_DIR=$3
echo $REPO_NAME>>repoNam.txt
echo $REPO_DIR>>repoDir.txt
fi
if [ $1 == 'ls' ]
then
echo "repo nicknames"
cat repoNam.txt
echo ""
echo "repo locations"
cat repoDir.txt
echo ""
fi
